#include <iostream>
using namespace std;

int main() {
  struct jual
  {
    string tipe;
    int jumlahkamar;
    float luas;
    float tinggi;
    string pemilik;
  };
  jual rumah[5];
  cout << "Masukkan Tipe Rumah = ";
  cin >> rumah[0].tipe;
  //cout << "Tipe Rumah= " << rumah.tipe <<endl;
  cout << "Masukkan Jumlah Kamar = ";
  cin >> rumah[0].jumlahkamar;
 // cout << "Jumlah Kamarnya Adalah = " << rumah.jumlahkamar << endl;
  cout << "Masukkan Luas Rumah = ";
  cin >> rumah[0].luas;
  //cout << "Luas Rumahnya Adalah = " << rumah.luas << endl;
  cout << "Masukkan Tinggi Rumah = ";
  cin >> rumah[0].tinggi;
  //cout << "Tinggi Rumahnya Adalah = " << rumah.tinggi << endl;
  cout << "Masukkan Pemilik Rumah = ";
  cin >> rumah[0].pemilik;
  //cout << "Pemilik Rumahnya Adalah = " << rumah.pemilik << endl;
  cout << endl <<endl;
  cout << "Tipe Rumah= " << rumah[0].tipe <<endl;
  cout << "Jumlah Kamarnya Adalah = " << rumah[0].jumlahkamar << endl;
  cout << "Luas Rumahnya Adalah = " << rumah[0].luas << endl;
  cout << "Tinggi Rumahnya Adalah = " << rumah[0].tinggi << endl;
  cout << "Pemilik Rumahnya Adalah = " << rumah[0].pemilik << endl;
  cout << endl;

  cout << "Masukkan Tipe Rumah = ";
  cin >> rumah[1].tipe;
  //cout << "Tipe Rumah= " << rumah.tipe <<endl;
  cout << "Masukkan Jumlah Kamar = ";
  cin >> rumah[1].jumlahkamar;
 // cout << "Jumlah Kamarnya Adalah = " << rumah.jumlahkamar << endl;
  cout << "Masukkan Luas Rumah = ";
  cin >> rumah[1].luas;
  //cout << "Luas Rumahnya Adalah = " << rumah.luas << endl;
  cout << "Masukkan Tinggi Rumah = ";
  cin >> rumah[1].tinggi;
  //cout << "Tinggi Rumahnya Adalah = " << rumah.tinggi << endl;
  cout << "Masukkan Pemilik Rumah = ";
  cin >> rumah[1].pemilik;
  //cout << "Pemilik Rumahnya Adalah = " << rumah.pemilik << endl;
  cout << endl <<endl;
  cout << "Tipe Rumah= " << rumah[1].tipe <<endl;
  cout << "Jumlah Kamarnya Adalah = " << rumah[1].jumlahkamar << endl;
  cout << "Luas Rumahnya Adalah = " << rumah[1].luas << endl;
  cout << "Tinggi Rumahnya Adalah = " << rumah[1].tinggi << endl;
  cout << "Pemilik Rumahnya Adalah = " << rumah[1].pemilik << endl;
  cout << endl;

  cout << "Masukkan Tipe Rumah = ";
  cin >> rumah[2].tipe;
  //cout << "Tipe Rumah= " << rumah.tipe <<endl;
  cout << "Masukkan Jumlah Kamar = ";
  cin >> rumah[2].jumlahkamar;
 // cout << "Jumlah Kamarnya Adalah = " << rumah.jumlahkamar << endl;
  cout << "Masukkan Luas Rumah = ";
  cin >> rumah[2].luas;
  //cout << "Luas Rumahnya Adalah = " << rumah.luas << endl;
  cout << "Masukkan Tinggi Rumah = ";
  cin >> rumah[2].tinggi;
  //cout << "Tinggi Rumahnya Adalah = " << rumah.tinggi << endl;
  cout << "Masukkan Pemilik Rumah = ";
  cin >> rumah[2].pemilik;
  //cout << "Pemilik Rumahnya Adalah = " << rumah.pemilik << endl;
  cout << endl <<endl;
  cout << "Tipe Rumah= " << rumah[2].tipe <<endl;
  cout << "Jumlah Kamarnya Adalah = " << rumah[2].jumlahkamar << endl;
  cout << "Luas Rumahnya Adalah = " << rumah[2].luas << endl;
  cout << "Tinggi Rumahnya Adalah = " << rumah[2].tinggi << endl;
  cout << "Pemilik Rumahnya Adalah = " << rumah[2].pemilik << endl;
  cout << endl;

  cout << "Masukkan Tipe Rumah = ";
  cin >> rumah[3].tipe;
  //cout << "Tipe Rumah= " << rumah.tipe <<endl;
  cout << "Masukkan Jumlah Kamar = ";
  cin >> rumah[3].jumlahkamar;
 // cout << "Jumlah Kamarnya Adalah = " << rumah.jumlahkamar << endl;
  cout << "Masukkan Luas Rumah = ";
  cin >> rumah[3].luas;
  //cout << "Luas Rumahnya Adalah = " << rumah.luas << endl;
  cout << "Masukkan Tinggi Rumah = ";
  cin >> rumah[3].tinggi;
  //cout << "Tinggi Rumahnya Adalah = " << rumah.tinggi << endl;
  cout << "Masukkan Pemilik Rumah = ";
  cin >> rumah[3].pemilik;
  //cout << "Pemilik Rumahnya Adalah = " << rumah.pemilik << endl;
  cout << endl <<endl;
  cout << "Tipe Rumah= " << rumah[3].tipe <<endl;
  cout << "Jumlah Kamarnya Adalah = " << rumah[3].jumlahkamar << endl;
  cout << "Luas Rumahnya Adalah = " << rumah[3].luas << endl;
  cout << "Tinggi Rumahnya Adalah = " << rumah[3].tinggi << endl;
  cout << "Pemilik Rumahnya Adalah = " << rumah[3].pemilik << endl;
  cout << endl;

  cout << "Masukkan Tipe Rumah = ";
  cin >> rumah[4].tipe;
  //cout << "Tipe Rumah= " << rumah.tipe <<endl;
  cout << "Masukkan Jumlah Kamar = ";
  cin >> rumah[4].jumlahkamar;
 // cout << "Jumlah Kamarnya Adalah = " << rumah.jumlahkamar << endl;
  cout << "Masukkan Luas Rumah = ";
  cin >> rumah[4].luas;
  //cout << "Luas Rumahnya Adalah = " << rumah.luas << endl;
  cout << "Masukkan Tinggi Rumah = ";
  
  cin >> rumah[4].tinggi;
  //cout << "Tinggi Rumahnya Adalah = " << rumah.tinggi << endl;
  cout << "Masukkan Pemilik Rumah = ";
  cin >> rumah[4].pemilik;
  //cout << "Pemilik Rumahnya Adalah = " << rumah.pemilik << endl;
  cout << endl <<endl;
  cout << "Tipe Rumah= " << rumah[4].tipe <<endl;
  cout << "Jumlah Kamarnya Adalah = " << rumah[4].jumlahkamar << endl;
  cout << "Luas Rumahnya Adalah = " << rumah[4].luas << endl;
  cout << "Tinggi Rumahnya Adalah = " << rumah[4].tinggi << endl;
  cout << "Pemilik Rumahnya Adalah = " << rumah[4].pemilik << endl;
  }